services:
  paddleocr:
    # --- 基础信息 ---
    image: baosight/self/cloud-audit/paddleocr:1.0.0
    container_name: paddleocr
    restart: always

    # --- 构建配置 ---
    build:
      context: paddleocr
      dockerfile: Dockerfile

    # --- 网络端口 ---
    networks:
      - cloud-audit
    ports:
      - "9999:80"

    # --- 数据挂载 ---
    volumes:
      - ./volumes/paddleocr/logs:/workspace/logs
      - ./volumes/paddleocr/data/temporary:/workspace/data/temporary
      - ./volumes/paddleocr/upload:/workspace/upload

  embedding:
    # --- 基础信息 ---
    image: baosight/self/cloud-audit/embedding:1.0.0
    container_name: embedding
    restart: always
    runtime: nvidia

    # --- 构建配置 ---
    build:
      context: embedding
      dockerfile: Dockerfile

    # --- 网络端口 ---
    networks:
      - cloud-audit
    ports:
      - "9000:80"

    # --- 数据挂载 ---
    volumes:
      - ./volumes/embedding/bce-embedding-base_v1:/workspace/bce-embedding-base_v1

  microsoft:
    # --- 基础信息 ---
    image: baosight/self/cloud-audit/microsoft:1.0.0
    container_name: microsoft
    restart: always

    # --- 构建配置 ---
    build:
      context: microsoft
      dockerfile: Dockerfile

    # --- 网络端口 ---
    networks:
      - cloud-audit
    ports:
      - "9001:80"

  codespace:
    # --- 基础信息 ---
    image: baosight/self/cloud-audit/codespace:1.0.0
    container_name: codespace
    restart: always

    # --- 构建配置 ---
    build:
      context: codespace
      dockerfile: Dockerfile

    # --- 网络端口 ---
    networks:
      - cloud-audit
    ports:
      - "10000:80"

    # --- 数据挂载 ---
    volumes:
      - ./volumes/codespace/instantclient_12_2:/opt/oracle/instantclient_12_2
      - ./volumes/codespace/workspace:/workspace

    # --- 环境变量 ---
    environment:
      - CODESPACE_HOST=${CODESPACE_HOST}
      - CODESPACE_PORT=${CODESPACE_PORT}
      - CODESPACE_BASE=${CODESPACE_BASE}

networks:
  cloud-audit:
    driver: bridge
